# comentario para testar
version: '3'
services:

  web01:
    build:
      context: ./web01
      dockerfile: Dockerfile
    image: web01
    container_name: web01
    restart: always
    tty: true
    networks:
      - asa-network

  web02:
    build:
      context: ./web02
      dockerfile: Dockerfile
    image: web02
    container_name: web02
    restart: always
    tty: true
    networks:
      - asa-network
      
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: proxy
    container_name: proxy
    hostname: www.asa.br
    restart: always
    tty: true
    ports:
      - "8080:80"
    depends_on:
      - web01
      - web02
    networks:
      - asa-network

  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    image: dns
    container_name: dns
    hostname: ns1.asa.br
    restart: always
    tty: true
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      - asa-network
 
#Docker Networks
networks:
  asa-network:
    driver: bridge